import React, { useState, useEffect } from 'react';
import { useApp } from '../AppContext';
import CandidateSelector from '../components/CandidateSelector';
import { BarChart3, Image, RefreshCw } from 'lucide-react';

const CHART_NAMES = [
  { file: 'overview.png',              label: 'Overview',              desc: 'Candidate overview radar' },
  { file: 'experience_timeline.png',   label: 'Experience Timeline',   desc: 'Career progression over time' },
  { file: 'publications_by_year.png',  label: 'Publications by Year',  desc: 'Research output over time' },
  { file: 'research_radar.png',        label: 'Research Radar',        desc: 'Multi-dimensional research profile' },
  { file: 'education_timeline.png',    label: 'Education Timeline',    desc: 'Academic progression' },
  { file: 'skills_distribution.png',   label: 'Skills Distribution',   desc: 'Skill category breakdown' },
];

// Maps candidate name to folder name as backend uses it
function candidateFolderName(fullName) {
  return (fullName || '').toUpperCase().replace(/\s+/g, '_');
}

export default function ChartsPage() {
  const { selectedCandidate: c } = useApp();
  const [available, setAvailable] = useState([]);
  const [selected, setSelected] = useState(null);
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});

  const folder = c ? candidateFolderName(c.full_name) : null;

  useEffect(() => {
    if (!folder) { setAvailable([]); setSelected(null); return; }
    setLoading(true);

    // Try to load each chart by probing the backend charts endpoint
    const check = async () => {
      const found = [];
      for (const chart of CHART_NAMES) {
        const url = `/charts/${folder}/${chart.file}`;
        try {
          const r = await fetch(url, { method: 'HEAD' });
          if (r.ok) found.push({ ...chart, url });
        } catch { /* not found */ }
      }
      setAvailable(found);
      if (found.length) setSelected(found[0]);
      setLoading(false);
    };
    check();
  }, [folder]);

  const handleImgError = (file) => {
    setErrors(prev => ({ ...prev, [file]: true }));
  };

  return (
    <div className="fade-up">
      <div className="page-header">
        <h1>Charts</h1>
        <p className="subtitle">Visual charts generated by the analysis pipeline for each candidate</p>
      </div>

      <CandidateSelector />

      {!c ? (
        <div className="card">
          <div className="empty-state">
            <BarChart3 size={32} />
            <h3>Select a candidate</h3>
            <p>Charts are loaded from <code style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>data/charts/&#123;CANDIDATE_NAME&#125;/</code></p>
          </div>
        </div>
      ) : loading ? (
        <div className="card">
          <div className="empty-state">
            <RefreshCw size={24} className="pulse" />
            <h3>Loading charts…</h3>
          </div>
        </div>
      ) : available.length === 0 ? (
        <div className="card">
          <div className="empty-state">
            <Image size={32} />
            <h3>No charts found</h3>
            <p>
              Expected at: <code style={{ fontFamily: 'var(--font-mono)', fontSize: 12, color: 'var(--accent)' }}>
                data/charts/{folder}/
              </code>
            </p>
            <p style={{ marginTop: 8 }}>Run the analysis pipeline first to generate charts.</p>
          </div>
        </div>
      ) : (
        <div className="grid-2" style={{ gap: 20 }}>
          {/* Chart selector list */}
          <div>
            <div className="card-title" style={{ marginBottom: 10 }}>Available charts ({available.length})</div>
            {CHART_NAMES.map(chart => {
              const avail = available.find(a => a.file === chart.file);
              const isSelected = selected?.file === chart.file;
              return (
                <div
                  key={chart.file}
                  onClick={() => avail && setSelected(avail)}
                  style={{
                    padding: '10px 14px',
                    marginBottom: 6,
                    borderRadius: 'var(--radius)',
                    border: `1px solid ${isSelected ? 'var(--accent)' : 'var(--border)'}`,
                    background: isSelected ? 'rgba(79,124,255,0.08)' : 'var(--bg2)',
                    cursor: avail ? 'pointer' : 'default',
                    opacity: avail ? 1 : 0.4,
                    transition: 'all 0.15s',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <BarChart3 size={14} color={isSelected ? 'var(--accent)' : 'var(--text3)'} />
                    <div>
                      <div style={{ fontSize: 13, fontWeight: isSelected ? 500 : 400 }}>{chart.label}</div>
                      <div style={{ fontSize: 11.5, color: 'var(--text3)', marginTop: 1 }}>{chart.desc}</div>
                    </div>
                    {avail
                      ? <span className="badge badge-green" style={{ marginLeft: 'auto' }}>Found</span>
                      : <span className="badge badge-red" style={{ marginLeft: 'auto' }}>Missing</span>
                    }
                  </div>
                </div>
              );
            })}
          </div>

          {/* Chart viewer */}
          <div className="card" style={{ display: 'flex', flexDirection: 'column' }}>
            {selected ? (
              <>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                  <div>
                    <div style={{ fontWeight: 500, fontSize: 14 }}>{selected.label}</div>
                    <div style={{ fontSize: 12, color: 'var(--text3)', marginTop: 2 }}>{selected.desc}</div>
                  </div>
                  <a
                    href={selected.url}
                    download={selected.file}
                    className="btn btn-ghost"
                    style={{ fontSize: 12, padding: '5px 12px' }}
                  >
                    Download
                  </a>
                </div>
                {errors[selected.file] ? (
                  <div className="empty-state" style={{ flex: 1 }}>
                    <Image size={24} />
                    <h3>Could not load image</h3>
                    <p style={{ fontFamily: 'var(--font-mono)', fontSize: 11 }}>{selected.url}</p>
                  </div>
                ) : (
                  <img
                    src={selected.url}
                    alt={selected.label}
                    className="chart-img"
                    onError={() => handleImgError(selected.file)}
                    style={{ flex: 1, objectFit: 'contain', maxHeight: 420 }}
                  />
                )}
              </>
            ) : (
              <div className="empty-state">
                <BarChart3 size={24} />
                <h3>Select a chart</h3>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}