import React, { useState, useEffect } from 'react';
import { useApp } from '../AppContext';
import CandidateSelector from '../components/CandidateSelector';
import { getCandidateCharts } from '../api';
import { BarChart3, Image, AlertCircle } from 'lucide-react';

// ── Helpers ───────────────────────────────────────────────────────────────────

function Spinner() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '40px 0', color: 'var(--text3)', fontSize: 13 }}>
      <div style={{ width: 18, height: 18, border: '2px solid var(--border2)', borderTopColor: 'var(--accent)', borderRadius: '50%', animation: 'spin 0.8s linear infinite' }} />
      Loading chart list…
    </div>
  );
}

// ── Main component ────────────────────────────────────────────────────────────
export default function ChartsPage() {
  const { selectedCandidate: c } = useApp();
  const [chartList, setChartList] = useState([]);
  const [selected, setSelected]   = useState(null);
  const [loading, setLoading]     = useState(false);
  const [error, setError]         = useState(null);
  const [imgError, setImgError]   = useState(false);

  useEffect(() => {
    if (!c?.candidate_id) { setChartList([]); setSelected(null); return; }
    setLoading(true);
    setError(null);
    setImgError(false);
    getCandidateCharts(c.candidate_id)
      .then(data => {
        setChartList(data.charts || []);
        setSelected(data.charts?.[0] || null);
        setLoading(false);
      })
      .catch(e => { setError(e.message); setLoading(false); });
  }, [c?.candidate_id]);

  return (
    <div className="fade-up">
      <div className="page-header">
        <h1>Charts</h1>
        <p className="subtitle">Visual charts generated by the analysis pipeline for each candidate</p>
      </div>

      <CandidateSelector />

      {!c ? (
        <div className="card">
          <div className="empty-state">
            <BarChart3 size={32} />
            <h3>Select a candidate</h3>
            <p>Charts are generated by running the pipeline and stored in <code style={{ fontFamily: 'var(--font-mono)', fontSize: 12 }}>data/charts/</code></p>
          </div>
        </div>
      ) : loading ? (
        <div className="card"><Spinner /></div>
      ) : error ? (
        <div className="card" style={{ display: 'flex', alignItems: 'center', gap: 10, color: 'var(--red)' }}>
          <AlertCircle size={18} /><span style={{ fontSize: 13 }}>{error}</span>
        </div>
      ) : chartList.length === 0 ? (
        <div className="card">
          <div className="empty-state">
            <Image size={32} />
            <h3>No charts found</h3>
            <p>Run the full analysis pipeline to generate charts for <strong>{c.full_name}</strong>.</p>
          </div>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: '240px 1fr', gap: 20 }}>
          {/* Chart list */}
          <div>
            <div style={{ fontSize: 11.5, color: 'var(--text3)', fontFamily: 'var(--font-mono)', marginBottom: 10 }}>
              {chartList.length} chart{chartList.length !== 1 ? 's' : ''} available
            </div>
            {chartList.map(chart => {
              const isSelected = selected?.file === chart.file;
              return (
                <div key={chart.file}
                  onClick={() => { setSelected(chart); setImgError(false); }}
                  style={{
                    padding: '10px 14px', marginBottom: 6, cursor: 'pointer',
                    borderRadius: 'var(--radius)',
                    border: `1px solid ${isSelected ? 'var(--accent)' : 'var(--border)'}`,
                    background: isSelected ? 'rgba(79,124,255,0.08)' : 'var(--bg2)',
                    transition: 'all 0.15s',
                  }}
                >
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <BarChart3 size={13} color={isSelected ? 'var(--accent)' : 'var(--text3)'} />
                    <span style={{ fontSize: 13, fontWeight: isSelected ? 500 : 400 }}>{chart.label}</span>
                  </div>
                  <div style={{ fontSize: 11, color: 'var(--text3)', marginTop: 2, fontFamily: 'var(--font-mono)' }}>
                    {chart.file}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Chart viewer */}
          <div className="card" style={{ display: 'flex', flexDirection: 'column', minHeight: 300 }}>
            {selected ? (
              <>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                  <div>
                    <div style={{ fontWeight: 500, fontSize: 14 }}>{selected.label}</div>
                    <div style={{ fontSize: 11.5, color: 'var(--text3)', marginTop: 2, fontFamily: 'var(--font-mono)' }}>
                      {selected.url}
                    </div>
                  </div>
                  <a href={selected.url} download={selected.file}
                    className="btn btn-ghost" style={{ fontSize: 12, padding: '5px 12px' }}>
                    Download
                  </a>
                </div>
                {imgError ? (
                  <div className="empty-state" style={{ flex: 1 }}>
                    <Image size={24} /><h3>Could not load image</h3>
                    <p style={{ fontFamily: 'var(--font-mono)', fontSize: 11 }}>{selected.url}</p>
                  </div>
                ) : (
                  <img
                    key={selected.url}
                    src={selected.url}
                    alt={selected.label}
                    onError={() => setImgError(true)}
                    style={{ flex: 1, objectFit: 'contain', maxHeight: 480, borderRadius: 4 }}
                  />
                )}
              </>
            ) : (
              <div className="empty-state"><BarChart3 size={24} /><h3>Select a chart</h3></div>
            )}
          </div>
        </div>
      )}

      <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
    </div>
  );
}
